name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy repo contents to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_IP }}
        username: ${{ secrets.DEPLOY_SERVER_USER }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        source: "."
        target: "/srv/htdocs/uhslc.soest.hawaii.edu/reservoir"
